CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    password TEXT
);

-- Insert users with hashed passwords (generated by PasswordHasher)
INSERT INTO users (username, password) VALUES ('admin', 'pA5k8SUvnV9bwxQLZdT7+52X5UB8DfDqCqsvJnVHM2E=');
INSERT INTO users (username, password) VALUES ('user', 'X03MO1qnZdYdgyfeuILPmQ==');
INSERT INTO users (username, password) VALUES ('guest', 'WnYS94EXHkn4AVuDAnfsnQ==');
